# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel

jobs:
  publish-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Docker
        uses: docker/setup-buildx-action@v1
      - id: auth
        name: Get Token For GCP Artifact Registry
        uses: google-github-actions/auth@v0
        with:
          token_format: access_token
          workload_identity_provider: ${{ secrets.PROVIDER }}
          service_account: ${{ secrets.SERVICE_EMAIL }}
      - name: Login to GCP Artifact Registry
        uses: docker/login-action@v1
        with:
          registry: europe-west3-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}
      - name: Get Package Version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
        with:
          path: app
      - name: Set Github NPM Credentials
        run: |
          echo "//npm.pkg.github.com/:_authToken=$NPM_TOKEN" > .npmrc
          echo '@Tripstagger-AA:registry=https://npm.pkg.github.com' >> .npmrc
        working-directory: ./app
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - id: docker_push
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: europe-west3-docker.pkg.dev/tripstagger-dev-346819/tripstagger-dev-346819-docker-registry/tripstagger-react-client:latest,europe-west3-docker.pkg.dev/tripstagger-dev-346819/tripstagger-dev-346819-docker-registry/tripstagger-react-client:${{ steps.package-version.outputs.current-version}}
  update-helm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get Package Version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
        with:
          path: app
      - name: Update version in helm chart
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PAT_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'Tripstagger-AA',
              repo: 'tripstagger-helm-chart',
              workflow_id: 'main.yml',
              ref: 'master'
            })